/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    folders: Folder;
    tags: Tag;
    projects: Project;
    experiences: Experience;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'folders';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'hero-section': HeroSection;
    'about-section': AboutSection;
    'contact-section': ContactSection;
    'footer-section': FooterSection;
  };
  globalsSelect: {
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
    'footer-section': FooterSectionSelect<false> | FooterSectionSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: (number | null) | Folder;
  tag?: (number | null) | Tag;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'folders';
          value: number | Folder;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'folders'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  category: string;
  /**
   * Direct link to project cover image (e.g. from ibb.co, imgur, or local public path)
   */
  imageLink: string;
  liveUrl?: string | null;
  githubUrl?: string | null;
  featured?: boolean | null;
  /**
   * Order of priority for featured projects (lower numbers come first)
   */
  featuredOrder?: number | null;
  /**
   * List the tech stack used in this project (e.g. Next.js, Tailwind, Postgres)
   */
  technologies: {
    name: string;
    id?: string | null;
  }[];
  /**
   * Select tags for this project (e.g. maksudur rahaman)
   */
  tags?: (number | Tag)[] | null;
  stats?: {
    stars?: number | null;
    users?: number | null;
    /**
     * Percentage of project completion (e.g., 100)
     */
    completion?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  /**
   * Emoji or simple icon string (e.g. 💼, 🔐, 🌍)
   */
  icon: string;
  title: string;
  company: string;
  /**
   * E.g., "Mar 2026 - Present" or "6 Months"
   */
  period: string;
  /**
   * E.g., "Bangladesh · Remote" or "Remote"
   */
  location: string;
  description: string;
  skills: {
    name: string;
    id?: string | null;
  }[];
  /**
   * Display order priority (lower numbers come first)
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  tag?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  imageLink?: T;
  liveUrl?: T;
  githubUrl?: T;
  featured?: T;
  featuredOrder?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  tags?: T;
  stats?:
    | T
    | {
        stars?: T;
        users?: T;
        completion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  company?: T;
  period?: T;
  location?: T;
  description?: T;
  skills?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  helloText: string;
  developerName: string;
  roles: {
    role: string;
    id?: string | null;
  }[];
  heading: string;
  description: string;
  skills: {
    name: string;
    /**
     * SVG URL or base64 data string for the skill icon
     */
    icon: string;
    id?: string | null;
  }[];
  cvUrl?: string | null;
  imageLink: string;
  linkedinUrl?: string | null;
  githubUrl?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  badgeText: string;
  title: string;
  description: string;
  introParagraphs: {
    paragraph: string;
    id?: string | null;
  }[];
  identityLabel: string;
  identityHeading: string;
  identityLocation: string;
  identityBulletPoints: {
    point: string;
    id?: string | null;
  }[];
  quoteText: string;
  stats: {
    number: string;
    label: string;
    id?: string | null;
  }[];
  features: {
    icon: 'Shield' | 'Code' | 'Database' | 'Zap';
    title: string;
    description: string;
    /**
     * CSS text color class (e.g. text-red-500 or text-purple-500)
     */
    color: string;
    id?: string | null;
  }[];
  education: {
    title: string;
    period: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  badgeText: string;
  title: string;
  description: string;
  conversationHeading: string;
  conversationText: string;
  email: string;
  phone: string;
  whatsapp: string;
  responseTime: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section".
 */
export interface FooterSection {
  id: number;
  badgeText: string;
  title: string;
  description: string;
  email: string;
  githubUrl: string;
  githubLabel: string;
  linkedinUrl: string;
  linkedinLabel: string;
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  helloText?: T;
  developerName?: T;
  roles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  heading?: T;
  description?: T;
  skills?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  cvUrl?: T;
  imageLink?: T;
  linkedinUrl?: T;
  githubUrl?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  badgeText?: T;
  title?: T;
  description?: T;
  introParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  identityLabel?: T;
  identityHeading?: T;
  identityLocation?: T;
  identityBulletPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  quoteText?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  education?:
    | T
    | {
        title?: T;
        period?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  badgeText?: T;
  title?: T;
  description?: T;
  conversationHeading?: T;
  conversationText?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  responseTime?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section_select".
 */
export interface FooterSectionSelect<T extends boolean = true> {
  badgeText?: T;
  title?: T;
  description?: T;
  email?: T;
  githubUrl?: T;
  githubLabel?: T;
  linkedinUrl?: T;
  linkedinLabel?: T;
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}